version: '3.7'

services:
    app-service:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
          - "8080:8080"
        restart: always
        depends_on:
          - db
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/polls?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
            SPRING_DATASOURCE_USERNAME: admin
            SPRING_DATAsOURCE_PASSWORD: admin
        networks:
          - backend

    db:
        image: mysql:5.7
        ports:
          - "3306:3306"
        restart: always
        environment:
            MYSQL_DATABASE: metal-service-db
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
        volumes:
          - db-data:/var/lib/mysql
        networks:
          - backend

    app-db:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - db
        ports:
            - 80:80
        environment:
            - PMA_ARBITRARY=1
        networks:
            - backend
volumes:
    db-data:

networks:
    backend: